### ISSUE TITLE
Doesn't work in Chrome

### ISSUE THREAD

**Issue by janez33** [lazarus-recovery/chrome_patched#2]
I installed this plugin beacuse I know it was the best plugin. But original version in chrome store doesn't support new version of chrome so I found this one and tried to installed it but I get some errors and it works in chrome but doesn't recover any form or input text :( Is this going to work some day or the original plugin will be updated?

**Comment by sierracircle** [comment]
We are currently focusing on updating the Firefox version. Once we have that worked out, we will update the Chrome version as well.
However, I am using the "Lazarus Form Recovery -Patched" from the Google Web Store, and it seems to be working okay for most forms, although I have noticed some field types seem to get skipped.

**Comment by janez33** [comment]
Thank you very much for that information, I can't wait to test new version when it comes out :)
