### ISSUE TITLE
What is necessary to make Lazarus Recovery reappear in Chrome?

### ISSUE THREAD

**Issue by benelot** [lazarus-recovery/chrome_patched#6]
Hello there!

I really liked the Lazarus Recovery extension and was sad when it was suddenly gone from the store. I would like to help out making it available again on the store. I am not sure if I am suitable as a maintainer after that, but I think getting it up and running would be a great start.

That is why I ask here:
* Is this the original source of the Lazarus Recovery Extension for Chrome?
* What is required to add it to the Chrome Store again?

**Comment by orschiro** [comment]
@benelot check https://chrome.google.com/webstore/detail/form-recovery/hbeeodhdgnjpdiioghaojiajkaomnjed.

**Comment by benelot** [comment]
Nice, thanks for doing this. Is this the version that is in this repository? Or are you maintaining it somewhere else? I think announcing it and allowing the community to help you maintain it would simplify the maintenance for you.

**Comment by orschiro** [comment]
> Nice, thanks for doing this. Is this the version that is in this repository? 

Yes. I just did some minor changes for the manifest file to validate.

> Or are you maintaining it somewhere else?

I forked it https://github.com/orschiro/form-recovery

> I think announcing it and allowing the community to help you maintain it would simplify the maintenance for you.

Ideally we all keep contributing to this parent repository. I will ensure to feed those improvements back to my fork which is then published onto the extension store.

**Comment by Billiam** [comment]
@orschiro It appears yours has now been removed from the Chrome store as well, why is that?

**Comment by orschiro** [comment]
I have no idea, sadly.

Billiam <notifications@github.com> schrieb am Mi. 19. Feb. 2020 um 20:52:

**Comment by benelot** [comment]
I think you need to reupload at some frequency for an extension to be considered "Maintained". Check if you can reactivate it again and upload a "new" version.

**Comment by devnoname120** [comment]
@orschiro Your fork still has a greyed out extension button on the current Chrome version (104.0.5112.79 (Official Build) (arm64)). Any ideas how to fix it?

**Comment by orschiro** [comment]
Sorry, but I currently don't have any time to work on a fix. :(

**Comment by sierracircle** [comment]
None of us are

**Comment by janez33** [comment]
RIP Lazarus 👋

**Comment by devnoname120** [comment]
I've been using [Form History Control (II)](https://github.com/stephanmahieu/formhistorycontrol-2) as an alternative and I haven't had any issues so far.
