### ISSUE TITLE
Settings get lost between Sessions

### ISSUE THREAD

**Issue by careca1970** [lazarus-recovery/chrome_patched#9]
Hi there!

I noticed that I am losing saved data from time to time.
It seems to be lost between browser sessions, but I am still not sure.
I must take more attention to this issue, and try to get a more accurate picture of the problem.
Oh yes, I usually set password for data bank encryption. Could it be the reason, does it even work properly?

Maybe anyone else has already a better explanation, on how it happens?!

**Comment by careca1970** [comment]
In fact, it might be due to the fact, that Forms are saved only up to 14 days. It is quite too short time...
It could be possible to set much longer period...

Thanks a lot for goos job!

**Comment by maphew** [comment]
thanks for coming back and telling us what you found, and the house-keeping of closing the issue. :-)
